# Generated by Django 4.2.11 on 2026-01-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformities', '0002_severity_alter_nonconformity_severity'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Severity',
        ),
    ]
