# Generated by Django 5.1.2 on 2024-11-12 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(db_column='Area_Id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Area_Descripcion', max_length=50)),
                ('codification', models.CharField(db_column='Area_Codificacion', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='Es_Id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Es_Descripcion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nonconformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('closure_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nonconformities.area')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nonconformities.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to=settings.AUTH_USER_MODEL)),
                ('severity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nonconformities.severity')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nonconformities.status')),
            ],
        ),
        migrations.CreateModel(
            name='NonconformityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='nonconformities.nonconformity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
