# Generated by Django 4.2.11 on 2026-01-26 17:32

from django.db import migrations, models
import django.db.models.deletion


def copy_severity_data(apps, schema_editor):
    """
    Copia los datos de core_severity a nonconformities_severity
    y actualiza las foreign keys en nonconformity.
    """
    # No podemos usar apps.get_model() porque el modelo ya no existe en core
    # Usamos SQL directo para copiar los datos
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Copiar datos de core_severity a nonconformities_severity
        cursor.execute("""
            INSERT INTO nonconformities_severity (id, name)
            SELECT id, name FROM core_severity
        """)
        print(f"✓ Copiados {cursor.rowcount} registros de Severity")


def reverse_copy_severity_data(apps, schema_editor):
    """
    Reversión: copiar de vuelta a core_severity (si se hace rollback).
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO core_severity (id, name)
            SELECT id, name FROM nonconformities_severity
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(copy_severity_data, reverse_copy_severity_data),
        migrations.AlterField(
            model_name='nonconformity',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nonconformities.severity'),
        ),
    ]
