# Generated by Django 5.1.2 on 2024-10-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('Area_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Area_Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('Es_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Es_Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencias_Cabeceras',
            fields=[
                ('In_Id', models.AutoField(primary_key=True, serialize=False)),
                ('In_Descripcion', models.TextField()),
                ('In_Fecha', models.DateTimeField(auto_now_add=True)),
                ('In_FechaCierre', models.DateTimeField(blank=True, null=True)),
                ('In_Codificacion', models.CharField(max_length=50)),
                ('In_Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.area')),
                ('In_Estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.estado')),
                ('In_Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencias_Lineas',
            fields=[
                ('Il_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Il_DesAccion', models.TextField()),
                ('Il_Fecha', models.DateTimeField(auto_now_add=True)),
                ('Id_Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('In_Cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='incidencias.incidencias_cabeceras')),
            ],
        ),
    ]
