# Generated by Django 5.1.2 on 2024-10-13 18:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidencias_Cabeceras',
            new_name='Incidencia_Cabecera',
        ),
        migrations.RenameModel(
            old_name='Incidencias_Lineas',
            new_name='Incidencia_Linea',
        ),
    ]
